---

- name: Installer PostgreSQL
  ansible.builtin.package: 
    name: 
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: yes

- name: S'assurer que le service PostgreSQL est démarré
  systemd:
    name: postgresql
    state: started
    enabled: true


- name: Créer l'utilisateur PostgreSQL "gvm"
  community.postgresql.postgresql_user:
    name: "{postgresql_user}"
    password: "Venus123@"
    role_attr_flags: "NOSUPERUSER"
    state: present
  become: false
  become_user: postgres

- name: Create a new database with name "{{ postgresql_db }}" 
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db }}"
    comment: My test DB
  become: false
  become_user: postgres


- name: Vérifier si le rôle gvm existe, sinon le créer
  postgresql_query:
    db: "{{ postgresql_db }}"
    query: >
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'gvm') THEN
          CREATE ROLE gvm LOGIN PASSWORD 'motdepasse' NOSUPERUSER;
        END IF;
      END
      $$;
  become: false
  become_user: postgres

- name: Créer le rôle dba avec superuser et sans héritage s'il n'existe pas
  postgresql_query:
    db: "{{ postgresql_db }}"
    query: >
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'dba') THEN
          CREATE ROLE dba WITH SUPERUSER NOINHERIT;
        END IF;
      END
      $$;
  become: false
  become_user: postgres

- name: Accorder le rôle dba à l'utilisateur "gvm"
  postgresql_query:
    db: "{{ postgresql_db }}"
    query: "GRANT dba TO gvm;"
  become: false
  become_user: postgres


- name: Accorder le rôle dba à l'utilisateur "{{ postgresql_user }}"
  postgresql_query:
    db: "{{ postgresql_db }}"
    query: "GRANT dba TO {{ postgresql_user }};"
  become: false
  become_user: postgres
